### ISSUE TITLE
Exhume Patch

### ISSUE THREAD

**Issue by KongMD-Steam** [MurderousDuck/FetchMod#1]
This could be applied to the Exhume card for Ironclad, as well. Would you patch that one? 

**Existing description:**
"Place a card from your exhaust pile into your hand. Exhaust."

**New description:**
"Fetch a card from your exhaust pile. Exhaust."

**Comment by MurderousDuck** [comment]
Before I thought it didn't make sense because fetching felt like getting a card that is there, and exhume gets a cart the supposedly got destroyed/burned but somehow the more I think about it, fetching a card from the "shadow realm" sounds badass, so patch will be done.

**Comment by MurderousDuck** [comment]
And bam, its now a Fetch card!
